language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "iulQmX6ImXmXDUK0XKTlnjB8/vVekiZzif7EYOXU3f8wGMxm/DQ/WIsX5hhrgMfkPLrAGblkZVR1tQEpw19fj7/xtWsyW2qWjDZxsLm++zalSyDXBy6CAIEK4980xsvx0/7tnIxz9eqqyD4bKSeQwEJ72Ab1LMBPDOOvHjZaGlw="
    - secure: "D6p9aHSP4Lzhe8CKfjNiD3sMatOEuK36LoFPd52A97NFkFSw3N1cqF0Crkz4uSHyBuunxS/c9aejoDmNowRgJ5x7g/Eg5f+tFZdxLwYHeZwMIxxSUiDODGo+kEEhL90l1rqTnzNqxynWcaXazIkNe+RvL+fiJyVlj9i72irMGmo="

branches:
  only:
    - master

install:
  - mvn -version -B

script:
  - mvn -fae install | grep -vF "Downloading:" | grep -vF "Downloaded:"

after_success:
  - test "${TRAVIS_PULL_REQUEST}" = "false" && mvn -s .travis.maven.settings.xml -DskipTests=true deploy

notifications:
  email: gbrown@redhat.com
